Fix recursion error in tox for allowlist_externals.
On GHA it was fine, but locally it was failing for me:

```
tox.report.HandledError: replace failed in py312.allowlist_externals with RecursionError('maximum recursion depth exceeded')
```

Might depend on the tox version.