Avoid AttributeError: 'NoneType' object has no attribute 'comments'.
This is when a '.po' file is missing an empty msgid and msgstr near
the top.  This is fixed automatically, although it will override some
headers.